# Use a builder argument to select the platform
ARG TARGETPLATFORM
ARG TARGETARCH

# Final image
FROM debian:stable-slim
ARG TARGETARCH
WORKDIR /app

# Copy the correct binary from the build context based on the target architecture
COPY ./bin/binary-${TARGETARCH} ./gemini-proxy

# Install root certificates for making HTTPS requests
RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*

# Expose the default port. The actual port is controlled by the .env file.
EXPOSE 3000

# Set the user and group to a non-root user for security
#RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser
#USER appuser

# Set environment variables for the application
# These should be provided at runtime, but we can set defaults
ENV APP_BASE_URL="http://0.0.0.0:3000"

# Forward proxy environment variables
# ARG HTTP_PROXY
# ARG HTTPS_PROXY
# ENV HTTP_PROXY=${HTTP_PROXY}
# ENV HTTPS_PROXY=${HTTPS_PROXY}

# The following need to be provided via --env-file or other means at runtime
# ENV GOOGLE_CLIENT_ID=""
# ENV GOOGLE_CLIENT_SECRET=""
# ENV OAUTH_CLIENT_ID=""
# ENV OAUTH_CLIENT_SECRET=""

# Command to run the application
CMD ["./gemini-proxy"]
